apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - petdoctor.kanearmstrong.com
    secretName: tls-secret
  rules:
  - host: petdoctor.kanearmstrong.com
    http:
      paths:
      - path: /api(/|$)(.*)
        backend:
          serviceName: {{ .Values.name }}-api-service
          servicePort: 80