apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}-api
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.petdoctor.api.port }}
---