config:
  petdoctor:appVersion: 0.0.2
  petdoctor:createdBy: Kane Armstrong
  petdoctor:environment: Development
  petdoctor:kubernetesVersion: 1.18.4
  petdoctor:sqlPassword:
    secure: AAABACeojBA4jnB0aEOPNQt7S1Ole6CYfUXja9En5q1qLZE0NRSaMHQYduHKNtW+2m3aovkWZDs=
  petdoctor:tenantId:
    secure: AAABAJoupYpemamNSqat8UiIdsk5F5MIGzVLPeQIXpXKawO0T/hVgQlyCfUrZV3kHyncc9bs/583iQhrcikdf37fPAo=
